CREATE VIEW MYVIEW AS SELECT * FROM EXEMP;
--VIEW
SELECT * FROM EXEMP;
--CREATE SIMPLE VIEW 
CREATE VIEW MYVIEW AS SELECT * FROM EXEMP;
CREATE OR REPLACE VIEW MYVIE1 AS SELECT * FROM EXEMP WHERE ENM='PRISHA';
--INSERT DATA INTO VIEW (but data added into table too
INSERT INTO MYVIEW VALUES(9,'VANSHIKA','15-NOV-2014',99999,'HR','VAN@GMAIL.COM');
--select 
select * from myview;
select * from exemp;
--drop view
DROP VIEW MYVIE1;

