--Sequence
--Creating a Sequence: Use the CREATE SEQUENCE statement to define a sequence.
create sequence priti_seq start with 1 increment by 2 maxvalue 500 minvalue 1 nocycle;
select * from exemp;
--Using NEXTVAL in a SELECT Query: You can also use NEXTVAL to fetch the next value in a sequence directly.
select priti_seq.nextval from dual;
--Using NEXTVAL in INSERT Statements: NEXTVAL generates the next number in the sequence, which can be used directly in an INSERT statement.
insert into exemp (eid,enm,esal) values (6,'Vivek',60000);
insert into exemp (eid,enm,esal) values (priti_seq.nextval,'rajat',60000);
insert into exemp (eid,enm,esal) values (priti_seq.nextval,'pramod',80000);
select * from exemp;
--Using CURRVAL: CURRVAL retrieves the most recent value generated by NEXTVAL in the current session. Note that NEXTVAL must be called first
--in the session before you can use CURRVAL.
select priti_seq.currval as "Current id" from dual;
--Altering a Sequence: To change the properties of an existing sequence, use the ALTER SEQUENCE statement.
alter sequence priti_seq increment by 5 maxvalue 1000;
insert into exemp (eid,enm,esal) values (priti_seq.nextval,'rohini',80000);
select * from exemp;
--drop sequence
drop sequence priti_seq;